name: Deploy Azure Infrastructure

on:
  workflow_dispatch:
  push:
    paths:
      - 'infra/**.bicep'
      - 'infra/**.bicepparam'
      - 'infra/**.json'
      - '.github/workflows/deploy-infra.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy Bicep template
        uses: azure/arm-deploy@v2
        with:
          resourceGroupName: ddb-ripper-tool
          template: infra/main.bicep
          parameters: infra/parameters.dev.json
          failOnStdErr: false

      - name: Logout from Azure
        run: az logout
